# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: vectordb.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'vectordb.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0evectordb.proto\x12\x08vectordb\"\x87\x01\n\x06Vector\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06values\x18\x02 \x03(\x02\x12\x30\n\x08metadata\x18\x03 \x03(\x0b\x32\x1e.vectordb.Vector.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"2\n\rInsertRequest\x12!\n\x07vectors\x18\x01 \x03(\x0b\x32\x10.vectordb.Vector\"\"\n\x0eInsertResponse\x12\x10\n\x08inserted\x18\x01 \x01(\x05\"\x8d\x01\n\rSearchRequest\x12\r\n\x05query\x18\x01 \x03(\x02\x12\t\n\x01k\x18\x02 \x01(\x05\x12\x33\n\x06\x66ilter\x18\x03 \x03(\x0b\x32#.vectordb.SearchRequest.FilterEntry\x1a-\n\x0b\x46ilterEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\xa5\x01\n\x0cSearchResult\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06values\x18\x02 \x03(\x02\x12\x10\n\x08\x64istance\x18\x03 \x01(\x02\x12\x36\n\x08metadata\x18\x04 \x03(\x0b\x32$.vectordb.SearchResult.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"9\n\x0eSearchResponse\x12\'\n\x07results\x18\x01 \x03(\x0b\x32\x16.vectordb.SearchResult\"\x1c\n\rDeleteRequest\x12\x0b\n\x03ids\x18\x01 \x03(\t\"!\n\x0e\x44\x65leteResponse\x12\x0f\n\x07\x64\x65leted\x18\x01 \x01(\x05\"\x0e\n\x0cStatsRequest\"M\n\rStatsResponse\x12\x15\n\rtotal_vectors\x18\x01 \x01(\x03\x12\x11\n\tdimension\x18\x02 \x01(\x05\x12\x12\n\nindex_size\x18\x03 \x01(\x03\x32\xfb\x01\n\x08VectorDB\x12;\n\x06Insert\x12\x17.vectordb.InsertRequest\x1a\x18.vectordb.InsertResponse\x12;\n\x06Search\x12\x17.vectordb.SearchRequest\x1a\x18.vectordb.SearchResponse\x12;\n\x06\x44\x65lete\x12\x17.vectordb.DeleteRequest\x1a\x18.vectordb.DeleteResponse\x12\x38\n\x05Stats\x12\x16.vectordb.StatsRequest\x1a\x17.vectordb.StatsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vectordb_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VECTOR_METADATAENTRY']._loaded_options = None
  _globals['_VECTOR_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_SEARCHREQUEST_FILTERENTRY']._loaded_options = None
  _globals['_SEARCHREQUEST_FILTERENTRY']._serialized_options = b'8\001'
  _globals['_SEARCHRESULT_METADATAENTRY']._loaded_options = None
  _globals['_SEARCHRESULT_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_VECTOR']._serialized_start=29
  _globals['_VECTOR']._serialized_end=164
  _globals['_VECTOR_METADATAENTRY']._serialized_start=117
  _globals['_VECTOR_METADATAENTRY']._serialized_end=164
  _globals['_INSERTREQUEST']._serialized_start=166
  _globals['_INSERTREQUEST']._serialized_end=216
  _globals['_INSERTRESPONSE']._serialized_start=218
  _globals['_INSERTRESPONSE']._serialized_end=252
  _globals['_SEARCHREQUEST']._serialized_start=255
  _globals['_SEARCHREQUEST']._serialized_end=396
  _globals['_SEARCHREQUEST_FILTERENTRY']._serialized_start=351
  _globals['_SEARCHREQUEST_FILTERENTRY']._serialized_end=396
  _globals['_SEARCHRESULT']._serialized_start=399
  _globals['_SEARCHRESULT']._serialized_end=564
  _globals['_SEARCHRESULT_METADATAENTRY']._serialized_start=117
  _globals['_SEARCHRESULT_METADATAENTRY']._serialized_end=164
  _globals['_SEARCHRESPONSE']._serialized_start=566
  _globals['_SEARCHRESPONSE']._serialized_end=623
  _globals['_DELETEREQUEST']._serialized_start=625
  _globals['_DELETEREQUEST']._serialized_end=653
  _globals['_DELETERESPONSE']._serialized_start=655
  _globals['_DELETERESPONSE']._serialized_end=688
  _globals['_STATSREQUEST']._serialized_start=690
  _globals['_STATSREQUEST']._serialized_end=704
  _globals['_STATSRESPONSE']._serialized_start=706
  _globals['_STATSRESPONSE']._serialized_end=783
  _globals['_VECTORDB']._serialized_start=786
  _globals['_VECTORDB']._serialized_end=1037
# @@protoc_insertion_point(module_scope)
